apiVersion: v1
kind: ConfigMap
metadata:
  name: sync
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  opslevel-k8s.yaml: |-
    {{ .Values.sync.config | nindent 4 }}